- id: '1550330341211'
  alias: Moho habitaci贸n
  trigger:
  - above: '75'
    entity_id: sensor.moho_dormitorio
    platform: numeric_state
  condition: []
  action:
  - service: notify.casacoru_bot
    data:
      message: La probabilidad de que se forme moho en la habitaci贸n es superior al
        75%; abre la ventana o pon el deshumificador.
- id: '1550330341212'
  alias: Moho habitaci贸n
  trigger:
  - above: '75'
    entity_id: sensor.moho_dormitorio
    platform: numeric_state
  condition: []
  action:
  - service: notify.casacoru_bot
    data:
      message: La probabilidad de que se forme moho en la habitaci贸n es superior al
        75%; abre la ventana o pon el deshumificador.

