# #Dark Sky
# - platform: darksky
#   api_key: !secret dark_api
#   monitored_conditions:
#     - summary
#     - nearest_storm_distance
#     - precip_probability
#     - apparent_temperature

# Weather prediction
- platform: yr
  monitored_conditions:
    - humidity
    - temperature

#World Air Quality Index
- platform: waqi
  token: !secret waqi_token
  locations:
    - a-coruna
    - vigo
  stations:
    - lope-de-vega
    - riazor

- platform: aemet
  name: AEMET
  api_key: !secret aemet_token
  station_id: !secret aemet_id
  monitored_conditions:
    - temperature
    - humidity
    - pressure
    - precipitation
    - snow
    - visibility
    - wind_speed
    - wind_bearing

- platform: co2signal
  token: !secret CO2SIGNAL