- platform: radarr_upcoming_media
  api_key: !secret radarr_api
  host: !secret dsm_host
  port: !secret radarr_port
  days: 120
  ssl: false
  theaters: false
  max: 10
- platform: sonarr_upcoming_media
  api_key: !secret sonarr_api
  host: !secret dsm_host
  port: !secret sonarr_port
  days: 120
  ssl: false
  max: 10
- platform: plex_recently_added
  name: Recently Added Movies
  token: secret plex_token
  host: !secret dsm_host
  port: !secret plex_port
  section_types:
    - movie
- platform: plex_recently_added
  name: Recently Added TV
  token: !secret plex_token
  host: !secret dsm_host
  port: !secret plex_port
  section_types:
    - show

- platform: radarr
  api_key: !secret radarr_api
  host: !secret dsm_host
  monitored_conditions:
    - upcoming
    - movies
    - commands
  days: 2
- platform: sonarr
  port: !secret sonarr_port
  api_key: !secret sonarr_api
  host: !secret dsm_host
  monitored_conditions:
    - upcoming
    - series
    - commands
  days: 2