sensor:
  # https://www.home-assistant.io/integrations/citybikes/
  - platform: citybikes
    name: Bicicletas públicas
    radius: 255
    # stations:
    #   - 123
    #   - 145
    #   - 436
  # https://www.home-assistant.io/integrations/google_travel_time/
  - platform: google_travel_time
    api_key: !secret secret_google
    origin: zone.home
    destination: Av. Ferrocarril, 2, A Coruña, Spain
    options:
      mode: transit
  - platform: google_travel_time
    api_key: !secret secret_google
    origin: zone.home
    destination: 36201, Praza Estación, 1, Vigo, Spain
    options:
      mode: driving
  # - platform: google_travel_time
  #   api_key: !secret secret_google
  #   origin: device_tracker.ruben
  #   destination: 36201, Praza Estación, 1, Vigo, Spain
  #   options:
  #     mode: driving

# automation: 
#   - id: update_morning_commute_sensor
#   alias: "Commute - Update morning commute sensor"
#   initial_state: 'on'
#   trigger:
#     - platform: time_pattern
#       minutes: '/2'
#   condition:
#     - condition: time
#       after: '08:00:00'
#       before: '11:00:00'
#     - condition: time
#       weekday:
#         - mon
#         - tue
#         - wed
#         - thu
#         - fri
#   action:
#     - service: homeassistant.update_entity
#       entity_id: sensor.morning_commute